default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spectre_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'postgres') %>
  host: db

test:
  <<: *default
  database: spectre_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'postgres') %>
  host: db

production:
  <<: *default
  database: spectre_production
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'postgres') %>
