default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tech_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'postgres') %>

test:
  <<: *default
  database: tech_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'postgres') %>


production:
  <<: *default
  database: tech_production
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'postgres') %>
