# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 796989a72b076ab3f05b1ab81934b3bb2ae59c8cc6cb6229353e9565a533bde28d6c4780a131987d3e7a41ad8c072bb04010c0ace4944266897b5a32e319890f

test:
  secret_key_base: 6977afe7ae027ba735b88642588e55a6c77e4bc2a5257ee9f1614d6528b4f50a143e5cf006de29f4433ffea7da3a4404d04e9b062b8a5fe8cfd6767b512f32fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
